/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NET.Barcode.Client;

namespace Cloudmersive.APIClient.NET.Barcode.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGenerateBarcodeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateBarcodeEAN13 (string value);

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateBarcodeEAN13WithHttpInfo (string value);
        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateBarcodeEAN8 (string value);

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateBarcodeEAN8WithHttpInfo (string value);
        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateBarcodeQRCode (string value);

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateBarcodeQRCodeWithHttpInfo (string value);
        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateBarcodeUPCA (string value);

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateBarcodeUPCAWithHttpInfo (string value);
        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateBarcodeUPCE (string value);

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateBarcodeUPCEWithHttpInfo (string value);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeEAN13Async (string value);

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeEAN13AsyncWithHttpInfo (string value);
        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeEAN8Async (string value);

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeEAN8AsyncWithHttpInfo (string value);
        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeQRCodeAsync (string value);

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeQRCodeAsyncWithHttpInfo (string value);
        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeUPCAAsync (string value);

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeUPCAAsyncWithHttpInfo (string value);
        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeUPCEAsync (string value);

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeUPCEAsyncWithHttpInfo (string value);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GenerateBarcodeApi : IGenerateBarcodeApi
    {
        private Cloudmersive.APIClient.NET.Barcode.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateBarcodeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GenerateBarcodeApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NET.Barcode.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateBarcodeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GenerateBarcodeApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NET.Barcode.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.Barcode.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateBarcodeEAN13 (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GenerateBarcodeEAN13WithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GenerateBarcodeEAN13WithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeEAN13");

            var localVarPath = "/barcode/generate/ean-13";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeEAN13", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeEAN13Async (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GenerateBarcodeEAN13AsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeEAN13AsyncWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeEAN13");

            var localVarPath = "/barcode/generate/ean-13";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeEAN13", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateBarcodeEAN8 (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GenerateBarcodeEAN8WithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GenerateBarcodeEAN8WithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeEAN8");

            var localVarPath = "/barcode/generate/ean-8";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeEAN8", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeEAN8Async (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GenerateBarcodeEAN8AsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeEAN8AsyncWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeEAN8");

            var localVarPath = "/barcode/generate/ean-8";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeEAN8", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateBarcodeQRCode (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GenerateBarcodeQRCodeWithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GenerateBarcodeQRCodeWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeQRCode");

            var localVarPath = "/barcode/generate/qrcode";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeQRCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeQRCodeAsync (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GenerateBarcodeQRCodeAsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">QR code text to convert into the QR code barcode</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeQRCodeAsyncWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeQRCode");

            var localVarPath = "/barcode/generate/qrcode";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeQRCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateBarcodeUPCA (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GenerateBarcodeUPCAWithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GenerateBarcodeUPCAWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeUPCA");

            var localVarPath = "/barcode/generate/upc-a";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeUPCA", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeUPCAAsync (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GenerateBarcodeUPCAAsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-A barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeUPCAAsyncWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeUPCA");

            var localVarPath = "/barcode/generate/upc-a";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeUPCA", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateBarcodeUPCE (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GenerateBarcodeUPCEWithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GenerateBarcodeUPCEWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeUPCE");

            var localVarPath = "/barcode/generate/upc-e";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeUPCE", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateBarcodeUPCEAsync (string value)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GenerateBarcodeUPCEAsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Barcode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">UPC-E barcode value to generate from</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateBarcodeUPCEAsyncWithHttpInfo (string value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling GenerateBarcodeApi->GenerateBarcodeUPCE");

            var localVarPath = "/barcode/generate/upc-e";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "image/png"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GenerateBarcodeUPCE", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

    }
}
