/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Barcode.Api;
using Cloudmersive.APIClient.NET.Barcode.Model;
using Cloudmersive.APIClient.NET.Barcode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Barcode.Test
{
    /// <summary>
    ///  Class for testing BarcodeAdvancedResultItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BarcodeAdvancedResultItemTests
    {
        // TODO uncomment below to declare an instance variable for BarcodeAdvancedResultItem
        //private BarcodeAdvancedResultItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BarcodeAdvancedResultItem
            //instance = new BarcodeAdvancedResultItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BarcodeAdvancedResultItem
        /// </summary>
        [Test]
        public void BarcodeAdvancedResultItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BarcodeAdvancedResultItem
            //Assert.IsInstanceOfType<BarcodeAdvancedResultItem> (instance, "variable 'instance' is a BarcodeAdvancedResultItem");
        }


        /// <summary>
        /// Test the property 'RawText'
        /// </summary>
        [Test]
        public void RawTextTest()
        {
            // TODO unit test for the property 'RawText'
        }
        /// <summary>
        /// Test the property 'BarcodeType'
        /// </summary>
        [Test]
        public void BarcodeTypeTest()
        {
            // TODO unit test for the property 'BarcodeType'
        }

    }

}
