/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Barcode.Api;
using Cloudmersive.APIClient.NET.Barcode.Model;
using Cloudmersive.APIClient.NET.Barcode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Barcode.Test
{
    /// <summary>
    ///  Class for testing BarcodeLookupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BarcodeLookupResponseTests
    {
        // TODO uncomment below to declare an instance variable for BarcodeLookupResponse
        //private BarcodeLookupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BarcodeLookupResponse
            //instance = new BarcodeLookupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BarcodeLookupResponse
        /// </summary>
        [Test]
        public void BarcodeLookupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BarcodeLookupResponse
            //Assert.IsInstanceOfType<BarcodeLookupResponse> (instance, "variable 'instance' is a BarcodeLookupResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Matches'
        /// </summary>
        [Test]
        public void MatchesTest()
        {
            // TODO unit test for the property 'Matches'
        }

    }

}
