/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Barcode.Api;
using Cloudmersive.APIClient.NET.Barcode.Model;
using Cloudmersive.APIClient.NET.Barcode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Barcode.Test
{
    /// <summary>
    ///  Class for testing BarcodeAdvancedScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BarcodeAdvancedScanResultTests
    {
        // TODO uncomment below to declare an instance variable for BarcodeAdvancedScanResult
        //private BarcodeAdvancedScanResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BarcodeAdvancedScanResult
            //instance = new BarcodeAdvancedScanResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BarcodeAdvancedScanResult
        /// </summary>
        [Test]
        public void BarcodeAdvancedScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BarcodeAdvancedScanResult
            //Assert.IsInstanceOfType<BarcodeAdvancedScanResult> (instance, "variable 'instance' is a BarcodeAdvancedScanResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ResultBarcodes'
        /// </summary>
        [Test]
        public void ResultBarcodesTest()
        {
            // TODO unit test for the property 'ResultBarcodes'
        }
        /// <summary>
        /// Test the property 'BarcodeCount'
        /// </summary>
        [Test]
        public void BarcodeCountTest()
        {
            // TODO unit test for the property 'BarcodeCount'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
