/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Barcode.Api;
using Cloudmersive.APIClient.NET.Barcode.Model;
using Cloudmersive.APIClient.NET.Barcode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Barcode.Test
{
    /// <summary>
    ///  Class for testing ProductMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductMatchTests
    {
        // TODO uncomment below to declare an instance variable for ProductMatch
        //private ProductMatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductMatch
            //instance = new ProductMatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductMatch
        /// </summary>
        [Test]
        public void ProductMatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductMatch
            //Assert.IsInstanceOfType<ProductMatch> (instance, "variable 'instance' is a ProductMatch");
        }


        /// <summary>
        /// Test the property 'EAN'
        /// </summary>
        [Test]
        public void EANTest()
        {
            // TODO unit test for the property 'EAN'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
