/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Barcode.Client;
using Cloudmersive.APIClient.NET.Barcode.Api;
using Cloudmersive.APIClient.NET.Barcode.Model;

namespace Cloudmersive.APIClient.NET.Barcode.Test
{
    /// <summary>
    ///  Class for testing BarcodeLookupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BarcodeLookupApiTests
    {
        private BarcodeLookupApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BarcodeLookupApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BarcodeLookupApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BarcodeLookupApi
            //Assert.IsInstanceOfType(typeof(BarcodeLookupApi), instance, "instance is a BarcodeLookupApi");
        }

        
        /// <summary>
        /// Test BarcodeLookupEanLookup
        /// </summary>
        [Test]
        public void BarcodeLookupEanLookupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.BarcodeLookupEanLookup(value);
            //Assert.IsInstanceOf<BarcodeLookupResponse> (response, "response is BarcodeLookupResponse");
        }
        
    }

}
