/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Barcode.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Barcode.Model
{
    /// <summary>
    /// BarcodeQRResultItem
    /// </summary>
    [DataContract]
    public partial class BarcodeQRResultItem :  IEquatable<BarcodeQRResultItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BarcodeQRResultItem" /> class.
        /// </summary>
        /// <param name="rawText">The barcode text.</param>
        public BarcodeQRResultItem(string rawText = default(string))
        {
            this.RawText = rawText;
        }
        
        /// <summary>
        /// The barcode text
        /// </summary>
        /// <value>The barcode text</value>
        [DataMember(Name="RawText", EmitDefaultValue=false)]
        public string RawText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BarcodeQRResultItem {\n");
            sb.Append("  RawText: ").Append(RawText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BarcodeQRResultItem);
        }

        /// <summary>
        /// Returns true if BarcodeQRResultItem instances are equal
        /// </summary>
        /// <param name="input">Instance of BarcodeQRResultItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BarcodeQRResultItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RawText == input.RawText ||
                    (this.RawText != null &&
                    this.RawText.Equals(input.RawText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RawText != null)
                    hashCode = hashCode * 59 + this.RawText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
