/* 
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Barcode.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Barcode.Model
{
    /// <summary>
    /// ProductMatch
    /// </summary>
    [DataContract]
    public partial class ProductMatch :  IEquatable<ProductMatch>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductMatch" /> class.
        /// </summary>
        /// <param name="eAN">eAN.</param>
        /// <param name="title">title.</param>
        public ProductMatch(string eAN = default(string), string title = default(string))
        {
            this.EAN = eAN;
            this.Title = title;
        }
        
        /// <summary>
        /// Gets or Sets EAN
        /// </summary>
        [DataMember(Name="EAN", EmitDefaultValue=false)]
        public string EAN { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="Title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductMatch {\n");
            sb.Append("  EAN: ").Append(EAN).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductMatch);
        }

        /// <summary>
        /// Returns true if ProductMatch instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductMatch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductMatch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EAN == input.EAN ||
                    (this.EAN != null &&
                    this.EAN.Equals(input.EAN))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EAN != null)
                    hashCode = hashCode * 59 + this.EAN.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
